## Equal Weights Strategy

In [1]:
import pandas as pd
import numpy as np
import yfinance as yf
import math

## Load the Stocks List

In [2]:
tickers = pd.read_csv('top_50_indian_stocks.csv')
tickers.head()

         Ticker               Company Name
0   RELIANCE.NS        Reliance Industries
1        TCS.NS  Tata Consultancy Services
2   HDFCBANK.NS                  HDFC Bank
3       INFY.NS                    Infosys
4  ICICIBANK.NS                 ICICI Bank

In [3]:
def fetch_market_cap(ticker_list):
    data = yf.download(ticker_list, period='1d', group_by='ticker', auto_adjust= False)
    
    stocks_data = []
    for ticker in ticker_list:
        latest_price = data[ticker]['Close'].iloc[-1] #fetching the latest price
        market_cap = yf.Ticker(ticker).info.get("marketCap", "N/A") # getting the m_cap from yf

        # Made a dictionary to store a key value pair of the name,m_cap and price
        stocks_data.append({
            "Ticker" : ticker,
            "Market Cap" : market_cap,
            "Latest Price" : latest_price,
        })

    stocks_df = pd.DataFrame(stocks_data)

    return stocks_df

ticker_list = tickers["Ticker"].values.tolist()
df = fetch_market_cap(ticker_list)
df.head()

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TATAMOTORS.NS"}}}
$TATAMOTORS.NS: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
[*********************100%***********************]  50 of 50 completed

1 Failed download:
['TATAMOTORS.NS']: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TATAMOTORS.NS"}}}

         Ticker      Market Cap  Latest Price
0   RELIANCE.NS  17543497515008   1293.000000
1        TCS.NS   7819049304064   2161.399902
2   HDFCBANK.NS  11886132199424    772.450012
3       INFY.NS   4528364584960   1116.400024
4  ICICIBANK.NS   9609688383488   1340.800049

In [4]:
df

           Ticker      Market Cap  Latest Price
0     RELIANCE.NS  17543497515008   1293.000000
1          TCS.NS   7819049304064   2161.399902
2     HDFCBANK.NS  11886132199424    772.450012
3         INFY.NS   4528364584960   1116.400024
4    ICICIBANK.NS   9609688383488   1340.800049
5   HINDUNILVR.NS   5081461161984   2168.800049
6         SBIN.NS   9381999542272   1017.150024
7   BAJFINANCE.NS   5720446599168    918.299988
8   BHARTIARTL.NS  11116935643136   1822.500000
9          ITC.NS   3579669381120    285.100006
10   KOTAKBANK.NS   4018372083712    403.299988
11    ADANIENT.NS   4026783498240   2921.600098
12          LT.NS   5571456532480   4049.300049
13     HCLTECH.NS   3003401109504   1109.599976
14  ASIANPAINT.NS   2626781184000   2747.399902
15    AXISBANK.NS   4208169844736   1356.300049
16   SUNPHARMA.NS   4335598305280   1807.699951
17       WIPRO.NS   1890812166144    180.139999
18  ULTRACEMCO.NS   3268224483328  11117.000000
19    HDFCLIFE.NS   1202001805312    555.349976
20        ONGC.NS   3106700001280    246.199997
21        NTPC.NS   3436498649088    353.899994
22   POWERGRID.NS   2650207158272    284.799988
23  TATAMOTORS.NS             N/A           NaN
24  INDUSINDBK.NS    714075144192    917.349976
25  ADANIGREEN.NS   2441279700992   1485.699951
26       TITAN.NS   3706962051072   4184.000000
27    DIVISLAB.NS   1760853098496   6638.000000
28       TECHM.NS   1269471903744   1429.199951
29      MARUTI.NS   4197274091520  13366.000000
30   COALINDIA.NS   2740873592832    443.500000
31        BPCL.NS   1292456951808    302.350006
32    JSWSTEEL.NS   3170634039296   1297.599976
33     DRREDDY.NS   1059948265472   1275.400024
34  BAJAJFINSV.NS   2704516317184   1689.099976
35  ADANIPORTS.NS   4168783495168   1812.900024
36       CIPLA.NS   1119673647104   1389.400024
37   BRITANNIA.NS   1246252498944   5165.500000
38     HAVELLS.NS    724544323584   1154.099976
39    SHREECEM.NS    872793309184  24175.000000
40      GRASIM.NS   2103759863808   3105.500000
41   TATASTEEL.NS   2467305619456    197.860001
42  HEROMOTOCO.NS    992460996608   4962.600098
43         M&M.NS   3650197127168   3042.899902
44   EICHERMOT.NS   2003832012800   7312.000000
45         IOC.NS   1993918775296    140.940002
46     SBICARD.NS    558594654208    589.450012
47  PIDILITIND.NS   1556992753664   1535.500000
48       DMART.NS   2607616098304   3993.600098
49     HDFCAMC.NS   1054058348544   2455.899902

In [5]:
df["Market Cap"] = pd.to_numeric(df["Market Cap"], errors="coerce") # changing every market cap to numeric as we may have n/a also
df = df.sort_values(by = "Market Cap", ascending = False) ## sorting every sto k based on their m cap
pd.options.display.float_format = '{:.0f}'.format
df

           Ticker     Market Cap  Latest Price
0     RELIANCE.NS 17543497515008          1293
2     HDFCBANK.NS 11886132199424           772
8   BHARTIARTL.NS 11116935643136          1822
4    ICICIBANK.NS  9609688383488          1341
6         SBIN.NS  9381999542272          1017
1          TCS.NS  7819049304064          2161
7   BAJFINANCE.NS  5720446599168           918
12          LT.NS  5571456532480          4049
5   HINDUNILVR.NS  5081461161984          2169
3         INFY.NS  4528364584960          1116
16   SUNPHARMA.NS  4335598305280          1808
15    AXISBANK.NS  4208169844736          1356
29      MARUTI.NS  4197274091520         13366
35  ADANIPORTS.NS  4168783495168          1813
11    ADANIENT.NS  4026783498240          2922
10   KOTAKBANK.NS  4018372083712           403
26       TITAN.NS  3706962051072          4184
43         M&M.NS  3650197127168          3043
9          ITC.NS  3579669381120           285
21        NTPC.NS  3436498649088           354
18  ULTRACEMCO.NS  3268224483328         11117
32    JSWSTEEL.NS  3170634039296          1298
20        ONGC.NS  3106700001280           246
13     HCLTECH.NS  3003401109504          1110
30   COALINDIA.NS  2740873592832           444
34  BAJAJFINSV.NS  2704516317184          1689
22   POWERGRID.NS  2650207158272           285
14  ASIANPAINT.NS  2626781184000          2747
48       DMART.NS  2607616098304          3994
41   TATASTEEL.NS  2467305619456           198
25  ADANIGREEN.NS  2441279700992          1486
40      GRASIM.NS  2103759863808          3106
44   EICHERMOT.NS  2003832012800          7312
45         IOC.NS  1993918775296           141
17       WIPRO.NS  1890812166144           180
27    DIVISLAB.NS  1760853098496          6638
47  PIDILITIND.NS  1556992753664          1536
31        BPCL.NS  1292456951808           302
28       TECHM.NS  1269471903744          1429
37   BRITANNIA.NS  1246252498944          5166
19    HDFCLIFE.NS  1202001805312           555
36       CIPLA.NS  1119673647104          1389
33     DRREDDY.NS  1059948265472          1275
49     HDFCAMC.NS  1054058348544          2456
42  HEROMOTOCO.NS   992460996608          4963
39    SHREECEM.NS   872793309184         24175
38     HAVELLS.NS   724544323584          1154
24  INDUSINDBK.NS   714075144192           917
46     SBICARD.NS   558594654208           589
23  TATAMOTORS.NS            NaN           NaN

## Taking Top 10 Stocks as per the Market Cap

In [6]:
df = df.head(10)  # it will take only 10 stocks which got sorted acc to their market cap
df = df.reset_index() # resets the index 
df

   index         Ticker     Market Cap  Latest Price
0      0    RELIANCE.NS 17543497515008          1293
1      2    HDFCBANK.NS 11886132199424           772
2      8  BHARTIARTL.NS 11116935643136          1822
3      4   ICICIBANK.NS  9609688383488          1341
4      6        SBIN.NS  9381999542272          1017
5      1         TCS.NS  7819049304064          2161
6      7  BAJFINANCE.NS  5720446599168           918
7     12          LT.NS  5571456532480          4049
8      5  HINDUNILVR.NS  5081461161984          2169
9      3        INFY.NS  4528364584960          1116

In [7]:
portfolio_size = int(input("Enter the Amount you want to Invest: "))
# to divide the money we will divide the money by the len of df here 10 as we taking top 10 stocks only. 
position_size = portfolio_size / len(df.index) # it will give how much i will invest in each stock
position_size

100000.0

In [8]:
df["Number Of Shares to buy"] = df['Latest Price'].apply(lambda price: math.floor(
    position_size / price
)) # could have written lambda price : position_size // price.

df

   index         Ticker     Market Cap  Latest Price  Number Of Shares to buy
0      0    RELIANCE.NS 17543497515008          1293                       77
1      2    HDFCBANK.NS 11886132199424           772                      129
2      8  BHARTIARTL.NS 11116935643136          1822                       54
3      4   ICICIBANK.NS  9609688383488          1341                       74
4      6        SBIN.NS  9381999542272          1017                       98
5      1         TCS.NS  7819049304064          2161                       46
6      7  BAJFINANCE.NS  5720446599168           918                      108
7     12          LT.NS  5571456532480          4049                       24
8      5  HINDUNILVR.NS  5081461161984          2169                       46
9      3        INFY.NS  4528364584960          1116                       89